create table if not exists public.daily_scores (
  id bigint generated by default as identity primary key,
  day text not null,
  name text not null,
  score int not null,
  distance int not null,
  replay jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists daily_scores_day_idx on public.daily_scores (day, score desc);

alter table public.daily_scores enable row level security;

drop policy if exists "puffwing read" on public.daily_scores;
create policy "puffwing read" on public.daily_scores
  for select to anon using (true);

drop policy if exists "puffwing insert" on public.daily_scores;
create policy "puffwing insert" on public.daily_scores
  for insert to anon with check (
    char_length(name) between 1 and 3
    and score between 0 and 999999
    and distance between 0 and 999999
    and char_length(day) = 10
    and jsonb_array_length(replay) between 4 and 4200
    and jsonb_array_length(replay) % 2 = 0
  );
